name: Branch Pipeline

on:
  pull_request:
    branches:
      - main

env:
  TF_IN_AUTOMATION: "True"

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.fmt.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt --check --recursive

  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    needs: format
    outputs:
      outcome: ${{ steps.validate.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="bucket=${{ vars.BACKEND_BUCKET }}" \
            -backend-config="key=${{ vars.BACKEND_KEY }}" \
            -backend-config="dynamodb_table=${{ vars.BACKEND_TABLE }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      outcome: ${{ steps.tflint.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="bucket=${{ vars.BACKEND_BUCKET }}" \
            -backend-config="key=${{ vars.BACKEND_KEY }}" \
            -backend-config="dynamodb_table=${{ vars.BACKEND_TABLE }}"

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        id: tflint
        continue-on-error: true
        run: tflint -f compact

  checkov:
    name: Checkov Code
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      outcome: ${{ steps.checkov.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true

  security:
    name: Secure Code
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      outcome: ${{ steps.tfsec.outcome }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run TFSec
        uses: aquasecurity/tfsec-action@v1.0.0
        id: tfsec
        continue-on-error: true

  plan:
    name: Plan Code
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      init: ${{ steps.init.outcome }}
      plan: ${{ steps.plan.outcome }}
      stdout: ${{ steps.plan.outputs.stdout }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="region=${{ secrets.AWS_REGION }}" \
            -backend-config="bucket=${{ vars.BACKEND_BUCKET }}" \
            -backend-config="key=${{ vars.BACKEND_KEY }}" \
            -backend-config="dynamodb_table=${{ vars.BACKEND_TABLE }}"

      - name: Terraform Plan
        id: plan
        continue-on-error: true
        run: |
          terraform plan -no-color -input=false

  finalize:
    name: Finalize Code
    runs-on: ubuntu-latest
    needs: [format, validate, lint, checkov, security, plan]
    steps:
      - name: Update Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const col1 = "${{ needs.plan.outputs.init }}";
            const col2 = "${{ needs.format.outputs.outcome }}";
            const col3 = "${{ needs.validate.outputs.outcome }}";
            const col4 = "${{ needs.lint.outputs.outcome }}";
            const col5 = "${{ needs.checkov.outputs.outcome }}";
            const col6 = "${{ needs.security.outputs.outcome }}";
            const col7 = "${{ needs.plan.outputs.plan }}";

            const output = `Terraform
            | Init ⚙️ | Format 🖌️ | Validation 🤖 | Lint 👁️ | Checkov ✅ | Security 🛡️ | Plan 📖 |
            | - | - | - | - | - | - | - |
            | ${col1} | ${col2} | ${col3} | ${col4} | ${col5} | ${col6} | ${col7} |

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${{ needs.plan.outputs.stdout }}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Result Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const outcomes = [
              "${{ needs.plan.outputs.init }}",
              "${{ needs.format.outputs.outcome }}",
              "${{ needs.validate.outputs.outcome }}",
              "${{ needs.lint.outputs.outcome }}",
              "${{ needs.checkov.outputs.outcome }}",
              "${{ needs.security.outputs.outcome }}",
              "${{ needs.plan.outputs.plan }}",
            ]

            const result = outcomes.every((outcome) => outcome === "success");

            if (!result) {
              core.setFailed("Some jobs have failed!")
            }
